# Generated by Django 5.2 on 2025-04-04 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comesc', '0002_state_address_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('composition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Composition')),
                ('yarn_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Yarn Cost')),
                ('knitting_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Knitting Cost')),
                ('dyeing_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dyeing Cost')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=15)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comesc.address')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
    ]
