# Generated by Django 5.2 on 2025-04-04 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comesc', '0003_material_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(default=12)),
                ('kg', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='comesc.supplier')),
            ],
        ),
    ]
