# Generated by Django 5.2 on 2025-04-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comesc', '0004_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='invoice',
            field=models.IntegerField(default=0),
        ),
    ]
