# Generated by Django 5.2 on 2025-04-07 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comesc', '0005_batch_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('ordem_producao', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em estoque', 'Em estoque'), ('com defeito', 'Com defeito')], default='pendente', max_length=15)),
                ('batch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='roll', to='comesc.batch')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='comesc.color')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll', to='comesc.material')),
            ],
        ),
    ]
