# Generated by Django 5.2 on 2025-04-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comesc', '0007_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
