# Generated by Django 5.2 on 2025-06-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comesc', '0008_delete_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roll',
            old_name='ordem_producao',
            new_name='production_order',
        ),
        migrations.RemoveField(
            model_name='roll',
            name='status',
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em estoque', 'Em estoque'), ('com defeito', 'Com defeito'), ('em transporte', 'Em transporte')], default='pendente', max_length=15),
        ),
        migrations.AddField(
            model_name='roll',
            name='nonconformity',
            field=models.BooleanField(default=False),
        ),
    ]
