# Generated by Django 5.2 on 2025-09-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comesc', '0009_rename_ordem_producao_roll_production_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='material',
        ),
        migrations.AddField(
            model_name='batch',
            name='composition',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='batch',
            name='material',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
