# Generated by Django 5.2 on 2025-09-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comesc', '0010_remove_roll_material_batch_composition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='production_order',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
