# Generated by Django 5.2 on 2025-09-07 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comesc', '0011_alter_roll_production_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='comesc.color'),
        ),
    ]
