# Generated by Django 5.2 on 2025-09-07 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comesc', '0012_alter_roll_color'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='uploader.image', verbose_name='cover'),
        ),
    ]
