# Generated by Django 5.2.7 on 2025-11-27 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comesc', '0013_batch_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='roll', to='comesc.batch'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='comesc.color'),
        ),
    ]
