# Generated by Django 5.1.7 on 2025-03-27 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('guests', models.IntegerField(default=1)),
                ('rooms', models.IntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to=settings.AUTH_USER_MODEL)),
                ('covers', models.ManyToManyField(related_name='hotel', to='uploader.image')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
    ]
