# Generated by Django 5.1.7 on 2025-03-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gohost', '0002_category_hotel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='hotel',
            name='type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('pousada', 'Pousada'), ('casa', 'Casa'), ('resort', 'Resort'), ('campings', 'Campings')], default='hotel', max_length=10),
        ),
    ]
