# Generated by Django 5.2 on 2025-04-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
