# Generated by Django 5.2.7 on 2025-11-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_usuario_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
